# Generated by Django 3.1.7 on 2021-03-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('zona_turistica', models.BooleanField()),
                ('codigo_postal', models.IntegerField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='AtractivosTuristicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda')),
                ('horarios', models.CharField(max_length=50)),
                ('precio_entrada', models.FloatField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ciudades')),
            ],
            options={
                'verbose_name': 'AtractivoTuristico',
                'verbose_name_plural': 'AtractivosTuristicos',
            },
        ),
    ]
